//! The v1 scope of the equation explorer (Addendum A decision 31): the dashboard, the
//! geometry callouts and the five chains, 159 paths plus the callouts (report section 7,
//! the chain lists of the A2 scope count). Every other result shows its label, value and
//! workbook cell. A path may sit in two chains; it has one record.
//!
//! Each batch of plan A-3 writes one chain's records and flips its status to `Explained`;
//! `tests/explain.rs` then requires a record for every path of every explained chain. The
//! geometry callouts are listed when the A1 view is specified (M4).

/// Whether a chain's records are written.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    Explained,
    Pending,
}

/// One chain (or the dashboard) of the v1 scope.
#[derive(Clone, Copy, Debug)]
pub struct Chain {
    pub id: &'static str,
    pub status: Status,
    pub paths: &'static [&'static str],
}

/// The v1 scope, in the spec's "start here" order, then the dashboard paths outside the chains.
pub const SCOPE: &[Chain] = &[
    Chain {
        id: "torque",
        status: Status::Explained,
        paths: &[
            "model.tau1_Pa",
            "model.tau3_Pa",
            "model.tau5_Pa",
            "model.tau_Pa",
            "calibration.tau1_Pa",
            "calibration.tau3_Pa",
            "calibration.tau5_Pa",
            "model.k1",
            "model.b_i1",
            "model.b_o1",
            "model.s1_iron",
            "model.s1_free",
            "model.k3",
            "model.b_i3",
            "model.b_o3",
            "model.s3_iron",
            "model.s3_free",
            "model.k5",
            "model.b_i5",
            "model.b_o5",
            "model.s5_iron",
            "model.s5_free",
            "model.area_lever_m3",
            "model.torque_2d_Nm",
            "model.pullout_Nm",
            "model.pullout_20C_Nm",
            "model.pullout_iron_Nm",
            "model.pullout_noiron_Nm",
            "calibration.torque_2d_Nm",
            "calibration.original_model_Nm",
            "calibration.model_torque_Nm",
            "model.f_end",
            "calibration.f_end",
            "model.f_cal",
            "calibration.f_cal_updated",
            "calibration.measured_over_model",
            "calibration.model_error",
            "calibration.fea_interp_Nm",
            "calibration.fea_interp_error",
            "metal.torque_op_Nm",
            "metal.torque_20C_Nm",
            "metal.torque_cold_Nm",
            "metal.torque_hot_low_Nm",
            "metal.torque_cold_high_Nm",
            "metal.hot_min_check",
            "metal.required_20C_Nm",
            "metal.hot_margin",
            "metal.required_20C_zero_scatter_Nm",
            "metal.torque_cold_zero_var_Nm",
            "metal.noiron_baseline_hot_Nm",
            "metal.cold_for_hot_min_Nm",
            "metal.cold_for_hot_min_input_Nm",
            "metal.cold_high_Nm",
            "metal.cold_high_input_Nm",
        ],
    },
    Chain {
        id: "temperature",
        status: Status::Pending,
        paths: &[
            "calibration.br_test_T",
            "model.inner_br_T",
            "model.outer_br_T",
            "model.alpha_br_per_C",
            "model.br_inner_T_op",
            "model.br_outer_T_op",
            "temperature.demag.br20_T",
            "temperature.demag.alpha_br",
            "metal.op_temp_C",
            "metal.alpha_br_per_C",
            "model.pullout_Nm",
            "model.pullout_20C_Nm",
            "metal.torque_op_Nm",
            "metal.torque_20C_Nm",
            "metal.torque_cold_Nm",
            "temperature.demag.torque_at_limit_Nm",
            "temperature.demag.torque_at_service_Nm",
            "temperature.summary.torque_hot_day_Nm",
            "temperature.summary.torque_hot_day_note",
            "temperature.magnet_life.torque_hot_day_Nm",
            "temperature.magnet_life.torque_hot_day_check",
            "temperature.magnet_life.torque_peak_Nm",
            "temperature.adhesive_life.torque_peak_var_Nm",
            "temperature.summary.service_max_C",
            "temperature.summary.onset_aligned_C",
            "temperature.summary.onset_pullout_C",
            "temperature.summary.onset_skipping_C",
            "temperature.summary.magnet_limit_C",
            "temperature.summary.adhesive_limit_C",
            "temperature.summary.governing_limit_C",
            "temperature.summary.governing_note",
            "temperature.summary.margin_service_C",
            "temperature.summary.hot_day_start_C",
            "temperature.summary.margin_hot_day_C",
            "temperature.summary.cure_margin_C",
            "temperature.summary.verdict",
            "temperature.demag.tmax_lib_C",
            "temperature.demag.magnet_limit_C",
            "model.inner_tmax_C",
            "model.outer_tmax_C",
            "model.inner_temp_check",
            "model.outer_temp_check",
            "temperature.adhesive.design_limit_C",
            "temperature.mismatch.cold_limit_C",
            "temperature.duty.hot_day_start_C",
        ],
    },
    Chain {
        id: "demagnetization",
        status: Status::Pending,
        paths: &[
            "temperature.demag.h_ref_kA_m",
            "temperature.demag.t_ref_model_C",
            "temperature.demag.calibration_offset_C",
            "temperature.demag.onset_aligned_C",
            "temperature.demag.onset_pullout_C",
            "temperature.demag.onset_skipping_C",
            "temperature.demag.onset_single_ring_C",
            "temperature.demag.magnet_limit_C",
            "temperature.summary.onset_aligned_C",
            "temperature.summary.onset_pullout_C",
            "temperature.summary.onset_skipping_C",
            "temperature.demag.torque_at_limit_Nm",
            "temperature.demag.torque_at_service_Nm",
            "temperature.summary.margin_service_C",
            "temperature.summary.margin_hot_day_C",
            "temperature.summary.cure_margin_C",
            "temperature.magnet_life.margin_onset_C",
            "temperature.magnet_life.margin_limit_C",
        ],
    },
    Chain {
        id: "slip_heating",
        status: Status::Pending,
        paths: &[
            "temperature.slip_loss.steel_sigma_S_m",
            "temperature.slip_loss.steel_mu_r",
            "temperature.slip_loss.cap_sigma_S_m",
            "temperature.slip_loss.skin_depth_mm",
            "temperature.slip_loss.hub_W",
            "temperature.slip_loss.cup_W",
            "temperature.slip_loss.web_W",
            "temperature.slip_loss.sleeve_W",
            "temperature.slip_loss.liner_W",
            "temperature.slip_loss.cap_W",
            "temperature.slip_loss.magnets_W",
            "temperature.slip_loss.total_W",
            "temperature.slip_loss.drag_Nm",
            "temperature.slip_loss.used_W",
            "temperature.slip_loss.high_W",
            "metal.slip_freq_Hz",
            "metal.slip_loss_W",
            "metal.slip_energy_J",
            "temperature.thermal.steel_c",
            "temperature.thermal.heat_capacity_J_K",
            "temperature.thermal.time_constant_s",
            "temperature.thermal.t95_s",
            "temperature.thermal.rev_per_tau",
            "temperature.thermal.rev95",
            "temperature.thermal.time_to_limit_high",
            "temperature.thermal.time_to_limit_est",
            "temperature.thermal.rotations_to_limit_high",
            "temperature.thermal.critical_drag_Nm",
            "temperature.summary.time_to_limit_high",
            "temperature.summary.critical_drag_Nm",
        ],
    },
    Chain {
        id: "clamps",
        status: Status::Pending,
        paths: &[
            "clamps.screw_proof_MPa",
            "clamps.joint_preload_N",
            "clamps.tightening_Nm",
            "clamps.table[].preload_strength_N",
            "clamps.table[].preload_strip_N",
            "clamps.table[].preload_N",
            "clamps.table[].tightening_Nm",
            "clamps.clamp_factor",
            "clamps.required_Nm",
            "clamps.max_torque_Nm",
            "clamps.screws",
            "clamps.capacity_Nm",
            "clamps.sf_coupling",
            "clamps.joint_torque_Nm",
            "clamps.joint_sf",
            "clamps.table[].torque_per_screw_Nm",
            "clamps.table[].screws_needed",
            "clamps.table[].clamp_torque_Nm",
            "clamps.table[].sf_coupling",
        ],
    },
    Chain {
        id: "dashboard",
        status: Status::Pending,
        paths: &[
            "model.gearbox_input_ripple_Nm",
            "model.cup_od_mm",
            "mass.total_g",
            "metal.min_running_clearance_mm",
            "metal.clearance_check",
            "materials.cup_wall_check",
            "clamps.recommended",
        ],
    },
];
